# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Shuhari
tagline:          'A better way to learn'
description:      'A blog detailing our exploits, ideas, and challenges as a company.'
url:              http://shuhari.io

author:
  name:           'Shuhari'
  url:            https://twitter.com/shuhari_io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
